
included:	 # paths to include during linting. `--path` is ignored if present.
  - BeeSwift
  - BeeSwiftToday

excluded:	 # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

reporter: "xcode"

disabled_rules: # rule identifiers to exclude from running
  - variable_name
  - type_name
  - empty_count

opt_in_rules: # some rules are only opt-in
  - control_statement
  - trailing_newline
  - colon
  - comma


shorthand_operator:
  severity: warning

force_cast:
  severity: warning

force_try:
  severity: warning

function_body_length:
  warning: 200
  error: 300

type_body_length:
  warning: 300
  error: 1000

file_length:
  warning: 500
  error: 1000

line_length:
  error: 500
