# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :test do
    run_tests(
        scheme: "BeeSwift",
        reset_simulator: true,
        xcodebuild_formatter: "xcpretty",
    )
  end
  lane :ci do
    sh("xcrun simctl delete all")
    sh("xcrun simctl create Test-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-2")
    run_tests(
        scheme: "BeeSwift",
        reset_simulator: true,
        include_simulator_logs: true,
        buildlog_path: "fastlane/test_output",
        xcodebuild_formatter: "xcpretty",
        devices: ["Test-iPhone"],
        ensure_devices_found: true,
    )
  end
  lane :build do
    build_app(scheme: "BeeSwift")
  end
  lane :beta do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "BeeSwift.xcodeproj"
    )
    
    build_app(scheme: "BeeSwift")

    # Commit the version bump
    commit_version_bump(xcodeproj: "BeeSwift.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote
    
    upload_to_testflight
  end
  lane :increment_major_version do
    increment_version_number(
      bump_type: "major",
      xcodeproj: "BeeSwift.xcodeproj"
    )
  end
  lane :increment_minor_version do
    increment_version_number(
      bump_type: "minor",
      xcodeproj: "BeeSwift.xcodeproj"
    )
  end
end
