name: Lint Sources


on:
  pull_request:
    paths:
      - '.github/workflows/lint-sources.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  lint:
    runs-on: macos-latest

    steps:
    - name: build config
      uses: actions/checkout@v2

    - name: Cache RubyGems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-

    - name: Install dependencies
      run: |
        gem install bundler:2.1.4
        bundle config path vendor/bundle
        bundle install
        bundle exec pod install

    - name: Lint code
      run: bundle exec fastlane lint

